# Generated by Django 5.1.4 on 2024-12-15 05:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('direccion_particular', models.CharField(max_length=255)),
                ('direccion_facturacion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('salt', models.CharField(blank=True, max_length=16, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('bloqueado', models.BooleanField(default=False)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('fecha_token', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=1000)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=0, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('categoria', models.CharField(choices=[('Postres', 'Postres'), ('Dulces', 'Dulces'), ('Bebidas', 'Bebidas'), ('Abarrotes', 'Abarrotes'), ('Alacena', 'Alacena'), ('Lacteos', 'Lácteos'), ('Aliños', 'Aliños'), ('Fiambreria', 'Fiambrería'), ('Limpieza', 'Limpieza'), ('Cereales', 'Cereales'), ('Snacks', 'Snacks'), ('Frutos Secos', 'Frutos Secos'), ('Panadería', 'Panadería'), ('Carnes', 'Carnes'), ('Vegetales', 'Vegetales')], max_length=50)),
                ('estado', models.CharField(choices=[('habilitado', 'Habilitado'), ('deshabilitado', 'Deshabilitado')], default='Habilitado', max_length=50)),
                ('admin_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Bodeguero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=16)),
                ('estado', models.BooleanField(default=True)),
                ('admin_id', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to='rincondelosvecinos.administrador')),
            ],
            options={
                'db_table': 'Bodeguero',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.DecimalField(decimal_places=0, max_digits=10)),
                ('preciodescuento', models.DecimalField(decimal_places=0, max_digits=10)),
                ('estado', models.CharField(choices=[('activa', 'inactiva')], max_length=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rincondelosvecinos.producto')),
            ],
            options={
                'db_table': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=16)),
                ('estado', models.BooleanField(default=True)),
                ('admin_id', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to='rincondelosvecinos.administrador')),
            ],
            options={
                'db_table': 'Vendedor',
            },
        ),
    ]
