# Generated by Django 5.1.2 on 2024-12-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rincondelosvecinos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodeguero',
            old_name='estado',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='vendedor',
            old_name='estado',
            new_name='is_active',
        ),
    ]
