# Generated by Django 5.1.2 on 2024-11-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rincondelosvecinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='salt',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
