# Generated by Django 5.1.2 on 2024-12-16 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rincondelosvecinos', '0002_rename_estado_bodeguero_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodeguero',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='is_active',
        ),
    ]
