# Generated by Django 5.1.2 on 2024-11-25 01:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rincondelosvecinos', '0002_administrador_salt'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='usuario',
        #     name='fecha_token',
        #     field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        # ),
        migrations.AlterField(
            model_name='administrador',
            name='salt',
            field=models.CharField(max_length=16),
        ),
    ]
