# Generated by Django 5.1.2 on 2024-12-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rincondelosvecinos', '0003_remove_bodeguero_is_active_remove_vendedor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodeguero',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
