# Generated by Django 5.1.2 on 2024-12-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rincondelosvecinos', '0004_bodeguero_estado_vendedor_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='inactiva', max_length=10),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='preciodescuento',
            field=models.IntegerField(default=0),
        ),
    ]
