# Generated by Django 5.1.4 on 2024-12-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rincondelosvecinos', '0004_producto_estado_usuario_fecha_token_and_more'),
    ]

    operations = [
        # migrations.AddField(
#     model_name='producto',
#     name='estado',
#     field=models.CharField(max_length=100),
# ),

    ]
